config/routes.rb
Rails.application.routes.draw do

  root 'users#login'
  
  resources :photos do
    get :like_photo
    post :comment, :view_comments, on: :collection
  end

  resources :users, :only => [:create]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :photos_users
  has_many :users, :through => :photos_users

  validates :file_name, :presence => true

  accepts_nested_attributes_for :photos_users
end

app/models/photos_user.rb
class PhotosUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo

  accepts_nested_attributes_for :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :photos_users
	has_many :photos, :through => :photos_users

	validates_length_of :username, within: 1..20, too_long: 'pick a shorter name', too_short: 'pick a longer name'
	validates :username, :presence => {:message => 'cannot be blank'}
	validates :username, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :view_comments]
  before_action :set_user

  # GET /photos
  # GET /photos.json
  def index
    #@photos = Photo.all
    #@photos_user = PhotosUser.where("user_id = ? AND is_owner = ? ", session[:user_id], 1)
    @my_photos = Photo.joins(:photos_users).where(photos_users: {user_id: session[:user_id], is_owner: 1} )
    
    @shared_photos = Photo.joins(:photos_users).where(photos_users: {user_id: session[:user_id], is_owner: nil} )
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @photo.photos_users.build
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        #Make entry for all shared users.
        shared_users = params[:users]
        #looping through all the users, and trimming the beginning and trailing spaces 
        shared_users.split(",").map(&:strip).each do |uname|
          #make an entry in the users if user doesn't exist
          @uname_obj = User.find_or_create_by!(username: uname)

          #make an entry in the mapping table
          PhotosUser.find_or_create_by!(user_id: @uname_obj.id, photo_id: @photo.id)
        end

        format.html { redirect_to photos_path, notice: 'Message was successfully Shared.' }
        format.json { render :index, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_photo
    @user.photos_users.where(:photo_id => params[:photo_id]).first.update_attributes(liked: true)
  end

  def comment
    @user.photos_users.where(:photo_id => params[:photo_id]).first.update_attributes(comment: params[:comment])
  end

  def view_comments
    @users_comments = @photo.photos_users.where("comment IS NOT NULL")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      id = params[:id] || params[:photo_id]
      @photo = Photo.find(id)
    end
    
    def set_user
      #get current user from session
      @user = User.find(session[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:users, :file_name, :file_path, :photos_users_attributes => [:user_id, :photo_id, :is_owner])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def login
		@user = User.new
	end
	
	def create
		@user = User.where(user_params).first_or_initialize

		respond_to do |format|
			if @user.save
			  session[:user_id] = @user.id
			  format.html { redirect_to photos_path, notice: 'User logged in successfully.' }
			else
			  format.html { render :login }
			end	
		end
  	end
  
  private
  
  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoSharing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="main_container">

<%= yield %>

</div>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Post your Message here : ' %><br>
    <%= f.text_area :file_name, size: "40x4" %>
  </div>
  
  <!--
  <div class="field">
    <%#= f.label :file_path %><br>
    <%#= f.text_field :file_path %>
  </div>
  -->

  <%= f.fields_for :photos_users do |photo_user| %>
    <%= photo_user.hidden_field :user_id, value: @user.id %>
    <%= photo_user.hidden_field :is_owner, value: 'true' %>
    <div class="field">
      <%= label_tag "List of Users you would like to Share (comma separated)" %><br>
      <%= text_field_tag :users %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Share Message', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/photos/_modal.html.erb
<div class="modal fade" id="myModal" role="dialog">
<div class="modal-dialog" style="width:400px;">   
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Add Your Comment</h4>
    </div>
    <div class="modal-body">
    	<textarea id="comment" name="photo[comment]" style="width:350px;"></textarea>
    	<input type="hidden" id="photo-id" name="photo[id]"></input>
    </div>
    <div class="modal-footer">
    <button type="button" id="save-comment" class="btn btn-primary" data-dismiss="modal">Save</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
  
</div>
</div>

app/views/photos/_view_comment_modal.html.erb
<div class="modal fade" id="viewCommentModal" role="dialog">
<div class="modal-dialog">   
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Available Comments</h4>
    </div>

    <div class="modal-body">
        <table class="table table-bordered">
          <thead>
            <tr>  <th>User Name</th> <th>Comment</th>  </tr>
          </thead>
          <tbody id="viewCommentModalBody" style="text-align:left">
          </tbody>
        </table>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
  
</div>
</div>

app/views/photos/comment.js.erb
photo_id = <%= params[:photo_id] %>
$("#comment_"+photo_id).replaceWith("<p> <%= params[:comment] %> </p>");
$("#comment").val(""); //resetting the value to null

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Welcome To the Page : <%= @user.username %></h2>

<div>
	<%= link_to "Post a Photo", new_photo_path, :class => "btn btn-primary pull-right" %>
</div>

<div class="container1">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#my-photos">My Gallery</a></li>
    <li><a data-toggle="tab" href="#shared-with-me">Shared With Me</a></li>
  </ul>

  <div class="tab-content">
    <div id="my-photos" class="tab-pane fade in active">
    	<br/>
    	<% if @my_photos.blank? %>
    		<p>You have not uploaded any messages, please click on Post a Photo to upload.</p>
    	<% else %>
    		<div class="row" style="margin: 0; width: 695px;">
			  <% @my_photos.each do |photo| %>
			    <div class="col-sm-4" style="height:150px; border: 1px solid black; border-collapse: collapse;text-align:left">
					<div class="msg-thumbnail" style="height:100px;">
						<%= photo.file_name %>
					</div>
					<div>
<!--						
						<% if photo.photos_users.where(user_id: @user.id, liked: true).present? %>
							<%= link_to "Liked", 'javascript:void(0)' %>
						<% else %>
							<%= link_to "Like", photo_like_photo_path(photo), remote: true, id: "like_#{photo.id}" %>
						<% end %>
-->	
						<%= photo.photos_users.where(liked: true).count %> Liked your post.
						<br/>
						<%= link_to "View comments", "javascript:void(0);", class: "view-comment", id: "view_comment_#{photo.id}", "data-photo": photo.id %>
					</div>
			    </div>
			  <% end %>
	  	</div>
    	<% end %>
    </div>

    <div id="shared-with-me" class="tab-pane fade">
    	<br/>
      	<% if @shared_photos.blank? %>
    		<p>No body has shared any upload with you. </p>
    	<% else %>
    		<div class="row" style="margin: 0; width: 695px;">
			  <% @shared_photos.each do |photo| %>
			    <div class="col-sm-4" style="height:150px; border: 1px solid black; border-collapse: collapse; text-align:left">
			    	<div class="msg-thumbnail" style="height:100px;">
						<%= photo.file_name %>
					</div>
					<div>
						<!-- Handle Like part-->
						<% if photo.photos_users.where(user_id: @user.id, liked: true).present? %>
							<p>You Liked this Message</p>
						<% else %>
							<%= link_to "Like", photo_like_photo_path(photo), remote: true, id: "like_#{photo.id}" %>
						<% end %>

						<!-- Handle Comment part now-->
						<%# if photo.photos_users.where(user_id: @user.id, comment: true).present? %>
				
						<% comment = photo.photos_users.select("comment").where(user_id: @user.id).first %>
						<% if comment.comment? %>
							<p><%= comment.comment %></p>
						<% else %>
							<%= link_to "Add Comment", "javascript:void(0);", class: "add-comment",id: "comment_#{photo.id}", "data-photo": photo.id %>	
						<% end %>
					</div>
			    </div>
			  <% end %>
	  		</div>
    	<% end %>
    </div>
  </div>

</div>

<%= render 'modal'%>
<%= render 'view_comment_modal'%>

app/views/photos/like_photo.js.erb
photo_id = <%= params[:photo_id] %>
//$("#like_"+photo_id).html('You Liked this message').attr('disabled', true).attr('href', 'javascript:void(0)');
$("#like_"+photo_id).replaceWith("<p>You Liked this message</p>");

app/views/photos/new.html.erb
<h1>Share Your Message</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path, :class => "btn btn-default" %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File name:</strong>
  <%= @photo.file_name %>
</p>

<p>
  <strong>File path:</strong>
  <%= @photo.file_path %>
</p>

<p>
  <strong>User:</strong>
  <%#= @photo.user.username %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/photos/view_comments.js.erb
<% if @users_comments.blank? %>
	$("#viewCommentModalBody").html("Comments not available.");
<% else %>
	$("#viewCommentModalBody").html("<%= j (render @users_comments) %>");
<% end %>

app/views/photos_users/_photos_user.html.erb
<tr>
  <td><%= photos_user.user.username %></td>
  <td><%= photos_user.comment %></td>
</tr>

app/views/users/login.html.erb
<h1>Login Page</h1>

<%= form_for @user, :as => :user, :url => users_path, :method => :post do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label 'Enter your Username :' %>
    <%= f.text_field :username %>
  </p>
  
  <p>
    <%= f.submit 'Log In', :class => "btn btn-primary" %>
    <%= f.button 'Clear Form', :class => "btn btn-default", :type => 'reset'%>
  </p>
<% end -%>